# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15014da6b6dd7803169a63318ca03c7976cdbf0bd55c58724d5b2bf00b96448fbbe99beb3dd16794e167e0b03fef1b7433578753b84a8f7bcb2b2e0cd9d7490f

test:
  secret_key_base: dc6c8e24bdac0fb1c29981ddabc98aeb18b1777f0847df86953d7183fc107c7eef43b863642a61c9ba738169296f85dffdb355e452194b4c96097c9200ea4a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
